### PR TITLE
Remove trailing spaces

### PR DESCRIPTION
**Pull request by LinusU**
To conform with Standard Style

### CODE REVIEW

**Comment by jprichardson** [comment]
Eeks, thanks! Will publish right now.

**Comment by jprichardson** [comment]
Published 2.0.1.

**Comment by LinusU** [comment]
Thank you!

**Comment by feross** [comment]
Nice, thanks 👍 For future reference, publishing to npm isn't necessary for the `standard` test suite. We use `git clone` :)

**Pull request merged**
